use crate::finding::{Finding, Severity};
use crate::{attack, deps, output, review, secrets, zeroday};
use anyhow::{Context, Result};
use colored::*;
use serde::Serialize;
use std::path::Path;

/// GitHub REST API base URL.
const GITHUB_API: &str = "https://api.github.com";

/// Collect all findings from every scanner (review, secrets, deps, zeroday).
/// Returns findings sorted by risk score, plus the attack-chain count.
pub(crate) async fn collect_pr_findings(
    project_path: &Path,
) -> Result<(Vec<Finding>, usize)> {
    let mut all = Vec::new();

    // Security review (pattern-based; no AI to keep the scan fast)
    if let Ok(report) = review::collect_review_findings(project_path, false, None).await {
        all.extend(report.findings);
    }
    // Secrets
    if let Ok(report) = secrets::collect_secrets_findings(project_path) {
        all.extend(report.findings);
    }
    // Dependencies
    if let Ok(report) = deps::collect_deps_findings(project_path, false).await {
        all.extend(report.findings);
    }
    // Zero-day flow + anomalies (no AI)
    if let Ok(report) = zeroday::collect_zeroday_findings(project_path, false, false).await {
        all.extend(report.to_finding_report().findings);
    }

    // Attack-chain count (informational)
    let attack_count = attack::collect_attack_summary(project_path).await.unwrap_or(0);

    // Deduplicate across scanners and sort by risk
    let deduped = crate::finding::dedup_findings(all);
    let mut sorted = deduped;
    sorted.sort_by(|a, b| {
        b.risk_score()
            .partial_cmp(&a.risk_score())
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    Ok((sorted, attack_count))
}

/// Severity counts helper.
fn severity_counts(findings: &[Finding]) -> (usize, usize, usize, usize) {
    let critical = findings.iter().filter(|f| f.severity == Severity::Critical).count();
    let high = findings.iter().filter(|f| f.severity == Severity::High).count();
    let medium = findings.iter().filter(|f| f.severity == Severity::Medium).count();
    let low = findings.iter().filter(|f| f.severity == Severity::Low).count();
    (critical, high, medium, low)
}

/// Render a markdown PR comment body from the collected findings.
pub(crate) fn render_pr_comment(findings: &[Finding], attack_count: usize, repo: &str, pr_number: u32) -> String {
    let (critical, high, medium, low) = severity_counts(findings);
    let total = findings.len();

    let mut md = String::new();

    md.push_str(&format!(
        "## 🔒 CipherAI Security Review — PR #{}\n\n",
        pr_number
    ));

    // Summary badges
    md.push_str("| Severity | Count |\n|----------|------:|\n");
    md.push_str(&format!("| 🔴 Critical | {} |\n", critical));
    md.push_str(&format!("| 🟠 High | {} |\n", high));
    md.push_str(&format!("| 🟡 Medium | {} |\n", medium));
    md.push_str(&format!("| 🔵 Low | {} |\n", low));
    md.push_str(&format!("| **Total** | **{}** |\n\n", total));

    if let Some(top) = findings.first() {
        md.push_str(&format!(
            "**Top risk:** {} ({:.0}/10)\n\n",
            top.title,
            top.risk_score()
        ));
    }

    md.push_str(&format!(
        "_Generated by [CipherAI](https://github.com/sandeepannandi/Cipher) — {} taint/attack chains detected._\n\n",
        attack_count
    ));

    if findings.is_empty() {
        md.push_str("✅ **No security issues found in this PR.**\n\n");
        md.push_str("> Tip: run `cipher-ai review --ai` locally for deeper AI-powered analysis.\n");
        return md;
    }

    // Top findings table
    md.push_str("### Findings\n\n");
    md.push_str("| # | Severity | Finding | CWE / OWASP | File:Line | Risk |\n");
    md.push_str("|---|----------|---------|-------------|-----------|-----:|\n");

    let max_show = findings.len().min(15);
    for (i, f) in findings.iter().take(max_show).enumerate() {
        let sev = match f.severity {
            Severity::Critical => "🔴 CRITICAL",
            Severity::High => "🟠 HIGH",
            Severity::Medium => "🟡 MEDIUM",
            Severity::Low => "🔵 LOW",
            Severity::Info => "⚪ INFO",
        };

        let ids = match (&f.cwe_id, f.owasp_category) {
            (Some(cwe), Some(owasp)) => format!("{} / {}", cwe, owasp.code()),
            (Some(cwe), None) => cwe.clone(),
            (None, Some(owasp)) => owasp.code().to_string(),
            (None, None) => "-".to_string(),
        };

        let loc = match (&f.file_path, f.line_number) {
            (Some(fp), Some(ln)) => format!("`{}:{}`", fp, ln),
            (Some(fp), None) => format!("`{}`", fp),
            (None, _) => "-".to_string(),
        };

        // Escape pipes in the title so the markdown table stays valid
        let title = f.title.replace('|', "\\|");
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} | {:.0}/10 |\n",
            i + 1,
            sev,
            title,
            ids,
            loc,
            f.risk_score()
        ));
    }

    if findings.len() > max_show {
        md.push_str(&format!(
            "| | | _+ {} more findings…_ | | | |\n",
            findings.len() - max_show
        ));
    }

    // Remediation highlights for the top 5
    let critical_high: Vec<&Finding> = findings
        .iter()
        .filter(|f| f.severity == Severity::Critical || f.severity == Severity::High)
        .collect();

    if !critical_high.is_empty() {
        md.push_str("\n### 🔧 Suggested fixes\n\n");
        for f in critical_high.iter().take(5) {
            md.push_str(&format!("- **{}** — ", f.title));
            if let Some(fp) = f.file_path.as_deref() {
                md.push_str(&format!("`{}`", fp));
                if let Some(ln) = f.line_number {
                    md.push_str(&format!(":{}", ln));
                }
                md.push_str(" — ");
            }
            md.push_str(
                f.remediation
                    .as_deref()
                    .unwrap_or("Review and fix manually."),
            );
            md.push('\n');
        }
    }

    md.push_str("\n---\n");
    md.push_str(&format!(
        "_[View full report](https://github.com/{}/actions) · Run `cipher-ai review --format sarif` for machine-readable output._\n",
        repo
    ));

    md
}

/// GitHub comment request body.
#[derive(Serialize)]
struct CommentBody {
    body: String,
}

/// Post a comment to a GitHub pull request.
pub(crate) async fn post_pr_comment(
    repo: &str,
    pr_number: u32,
    token: &str,
    body: &str,
) -> Result<()> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .user_agent("cipher-ai/1.0")
        .build()
        .context("Failed to build HTTP client")?;

    let url = format!("{}/repos/{}/issues/{}/comments", GITHUB_API, repo, pr_number);

    let response = client
        .post(&url)
        .bearer_auth(token)
        .header("Accept", "application/vnd.github+json")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .json(&CommentBody { body: body.to_string() })
        .send()
        .await
        .context("Failed to send comment to GitHub")?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        anyhow::bail!(
            "GitHub API error ({}) posting to {}#{}: {}",
            status,
            repo,
            pr_number,
            text
        );
    }

    Ok(())
}

/// Resolve the repo (owner/name) from CLI arg or environment.
fn resolve_repo(repo: Option<&str>) -> Option<String> {
    repo.map(|s| s.to_string())
        .or_else(|| std::env::var("GITHUB_REPOSITORY").ok())
}

/// Resolve the PR number from CLI arg or environment (GITHUB_PR_NUMBER,
/// or parse GITHUB_REF `refs/pull/N/merge`).
fn resolve_pr_number(pr_number: Option<u32>) -> Option<u32> {
    if let Some(n) = pr_number {
        return Some(n);
    }
    if let Ok(n) = std::env::var("GITHUB_PR_NUMBER") {
        if let Ok(parsed) = n.parse::<u32>() {
            return Some(parsed);
        }
    }
    if let Ok(github_ref) = std::env::var("GITHUB_REF") {
        // refs/pull/42/merge
        let parts: Vec<&str> = github_ref.split('/').collect();
        if parts.len() >= 3 && parts[0] == "refs" && parts[1] == "pull" {
            if let Ok(parsed) = parts[2].parse::<u32>() {
                return Some(parsed);
            }
        }
    }
    None
}

/// Run the `cipher-ai pr` command — review a pull request and comment.
pub async fn run_pr(
    project_path: &Path,
    repo: Option<&str>,
    pr_number: Option<u32>,
    token: Option<&str>,
    dry_run: bool,
) -> Result<()> {
    let canonical_path = std::fs::canonicalize(project_path)?;

    output::print_header("PR Security Review", Some(&canonical_path.display().to_string()));

    // Resolve repo + PR number
    let repo = match resolve_repo(repo) {
        Some(r) => r,
        None => {
            anyhow::bail!(
                "Could not determine repository. Pass --repo owner/name or set GITHUB_REPOSITORY."
            )
        }
    };
    let pr_number = match resolve_pr_number(pr_number) {
        Some(n) => n,
        None => {
            anyhow::bail!(
                "Could not determine PR number. Pass --pr N or set GITHUB_PR_NUMBER / GITHUB_REF."
            )
        }
    };
    let token = match token {
        Some(t) => t.to_string(),
        None => match std::env::var("GITHUB_TOKEN").or_else(|_| std::env::var("GH_TOKEN")) {
            Ok(t) => t,
            Err(_) => anyhow::bail!(
                "No GitHub token found. Pass --token or set GITHUB_TOKEN.\n\
                 Tokens need the `repo` scope to comment on PRs."
            ),
        },
    };

    println!(
        "  {} Reviewing {} #{}...\n",
        "[GITHUB]".cyan(),
        repo.yellow(),
        pr_number.to_string().yellow().bold()
    );

    // Step 1: run the scan suite
    output::print_step(1, 3, "Running security scans (review + secrets + deps + zeroday)");
    let (findings, attack_count) = collect_pr_findings(&canonical_path).await?;
    let (critical, high, medium, low) = severity_counts(&findings);
    output::print_ok("Scans", &format!(
        "{} critical, {} high, {} medium, {} low, {} total",
        critical.to_string().red().bold(),
        high.to_string().yellow().bold(),
        medium.to_string().cyan(),
        low.to_string().dimmed(),
        findings.len().to_string().bold()
    ));

    // Step 2: render the comment
    output::print_step(2, 3, "Rendering review comment");
    let comment = render_pr_comment(&findings, attack_count, &repo, pr_number);

    // Step 3: dry-run or post
    if dry_run {
        output::print_step(3, 3, "Dry-run mode — comment not posted");
        println!();
        println!("{}", comment);
        println!();
        output::print_ok("Dry-run", "Rerun without --dry-run to post this comment to the PR.");
        return Ok(());
    }

    output::print_step(3, 3, "Posting comment to GitHub");
    match post_pr_comment(&repo, pr_number, &token, &comment).await {
        Ok(()) => {
            output::print_success(&format!(
                "Comment posted to {}/pull/{}",
                repo,
                pr_number
            ));
        }
        Err(e) => {
            output::print_fail("GitHub", &e.to_string());
            anyhow::bail!(e);
        }
    }

    output::print_footer();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finding::{Confidence, FindingType};

    fn mk(title: &str, sev: Severity, cwe: &str, file: &str, line: usize) -> Finding {
        Finding::new(
            FindingType::Vulnerability,
            title,
            "desc",
            sev,
            Confidence::High,
            "test",
        )
        .at(file, line)
        .with_cwe(cwe)
    }

    #[test]
    fn test_severity_counts() {
        let findings = vec![
            mk("A", Severity::Critical, "CWE-89", "a.py", 1),
            mk("B", Severity::High, "CWE-78", "b.py", 2),
            mk("C", Severity::Medium, "CWE-22", "c.py", 3),
            mk("D", Severity::Low, "CWE-79", "d.py", 4),
        ];
        let (c, h, m, l) = severity_counts(&findings);
        assert_eq!((c, h, m, l), (1, 1, 1, 1));
    }

    #[test]
    fn test_render_pr_comment_empty() {
        let md = render_pr_comment(&[], 0, "owner/repo", 1);
        assert!(md.contains("No security issues found"));
        assert!(md.contains("PR #1"));
    }

    #[test]
    fn test_render_pr_comment_with_findings() {
        let findings = vec![
            mk("SQL Injection in query", Severity::Critical, "CWE-89", "app/query.py", 42),
            mk("Weak MD5 hash", Severity::High, "CWE-328", "app/hash.py", 7),
        ];
        let md = render_pr_comment(&findings, 3, "owner/repo", 12);
        assert!(md.contains("PR #12"));
        assert!(md.contains("CWE-89"));
        assert!(md.contains("SQL Injection"));
        assert!(md.contains("3 taint/attack chains"));
        assert!(md.contains("Suggested fixes"));
    }

    #[test]
    fn test_resolve_pr_number_env() {
        // Env var path
        std::env::set_var("GITHUB_PR_NUMBER", "42");
        assert_eq!(resolve_pr_number(None), Some(42));
        std::env::remove_var("GITHUB_PR_NUMBER");

        // GITHUB_REF path
        std::env::set_var("GITHUB_REF", "refs/pull/99/merge");
        assert_eq!(resolve_pr_number(None), Some(99));
        std::env::remove_var("GITHUB_REF");

        // Explicit arg wins
        std::env::set_var("GITHUB_PR_NUMBER", "42");
        assert_eq!(resolve_pr_number(Some(7)), Some(7));
        std::env::remove_var("GITHUB_PR_NUMBER");
    }

    #[test]
    fn test_render_comment_escapes_pipes() {
        let mut f = mk("A | B", Severity::High, "CWE-89", "a.py", 1);
        f.title = "Injection | Danger".to_string();
        let md = render_pr_comment(&[f], 0, "o/r", 5);
        assert!(md.contains("Injection \\| Danger"));
    }
}
