use crate::finding::{Finding, Severity};
use crate::{attack, deps, output, review, secrets, zeroday};
use anyhow::{Context, Result};
use colored::*;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// GitHub REST API base URL.
const GITHUB_API: &str = "https://api.github.com";

/// Collect all findings from every scanner (review, secrets, deps, zeroday).
/// Returns findings sorted by risk score, plus the attack-chain count.
pub(crate) async fn collect_pr_findings(
    project_path: &Path,
) -> Result<(Vec<Finding>, usize)> {
    let mut all = Vec::new();

    // Security review (pattern-based; no AI to keep the scan fast)
    if let Ok(report) = review::collect_review_findings(project_path, false, None).await {
        all.extend(report.findings);
    }
    // Secrets
    if let Ok(report) = secrets::collect_secrets_findings(project_path) {
        all.extend(report.findings);
    }
    // Dependencies
    if let Ok(report) = deps::collect_deps_findings(project_path, false).await {
        all.extend(report.findings);
    }
    // Zero-day flow + anomalies (no AI)
    if let Ok(report) = zeroday::collect_zeroday_findings(project_path, false, false).await {
        all.extend(report.to_finding_report().findings);
    }

    // Attack-chain count (informational)
    let attack_count = attack::collect_attack_summary(project_path).await.unwrap_or(0);

    // Deduplicate across scanners and sort by risk
    let deduped = crate::finding::dedup_findings(all);
    let mut sorted = deduped;
    sorted.sort_by(|a, b| {
        b.risk_score()
            .partial_cmp(&a.risk_score())
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    Ok((sorted, attack_count))
}

/// Severity counts helper.
fn severity_counts(findings: &[Finding]) -> (usize, usize, usize, usize) {
    let critical = findings.iter().filter(|f| f.severity == Severity::Critical).count();
    let high = findings.iter().filter(|f| f.severity == Severity::High).count();
    let medium = findings.iter().filter(|f| f.severity == Severity::Medium).count();
    let low = findings.iter().filter(|f| f.severity == Severity::Low).count();
    (critical, high, medium, low)
}

/// Render a markdown PR comment body from the collected findings.
pub(crate) fn render_pr_comment(findings: &[Finding], attack_count: usize, repo: &str, pr_number: u32) -> String {
    let (critical, high, medium, low) = severity_counts(findings);
    let total = findings.len();

    let mut md = String::new();

    md.push_str(&format!(
        "## 🔒 CipherAI Security Review — PR #{}\n\n",
        pr_number
    ));

    // Summary badges
    md.push_str("| Severity | Count |\n|----------|------:|\n");
    md.push_str(&format!("| 🔴 Critical | {} |\n", critical));
    md.push_str(&format!("| 🟠 High | {} |\n", high));
    md.push_str(&format!("| 🟡 Medium | {} |\n", medium));
    md.push_str(&format!("| 🔵 Low | {} |\n", low));
    md.push_str(&format!("| **Total** | **{}** |\n\n", total));

    if let Some(top) = findings.first() {
        md.push_str(&format!(
            "**Top risk:** {} ({:.0}/10)\n\n",
            top.title,
            top.risk_score()
        ));
    }

    md.push_str(&format!(
        "_Generated by [CipherAI](https://github.com/sandeepannandi/Cipher) — {} taint/attack chains detected._\n\n",
        attack_count
    ));

    if findings.is_empty() {
        md.push_str("✅ **No security issues found in this PR.**\n\n");
        md.push_str("> Tip: run `cipher-ai review --ai` locally for deeper AI-powered analysis.\n");
        return md;
    }

    // Top findings table
    md.push_str("### Findings\n\n");
    md.push_str("| # | Severity | Finding | CWE / OWASP | File:Line | Risk |\n");
    md.push_str("|---|----------|---------|-------------|-----------|-----:|\n");

    let max_show = findings.len().min(15);
    for (i, f) in findings.iter().take(max_show).enumerate() {
        let sev = match f.severity {
            Severity::Critical => "🔴 CRITICAL",
            Severity::High => "🟠 HIGH",
            Severity::Medium => "🟡 MEDIUM",
            Severity::Low => "🔵 LOW",
            Severity::Info => "⚪ INFO",
        };

        let ids = match (&f.cwe_id, f.owasp_category) {
            (Some(cwe), Some(owasp)) => format!("{} / {}", cwe, owasp.code()),
            (Some(cwe), None) => cwe.clone(),
            (None, Some(owasp)) => owasp.code().to_string(),
            (None, None) => "-".to_string(),
        };

        let loc = match (&f.file_path, f.line_number) {
            (Some(fp), Some(ln)) => format!("`{}:{}`", fp, ln),
            (Some(fp), None) => format!("`{}`", fp),
            (None, _) => "-".to_string(),
        };

        // Escape pipes in the title so the markdown table stays valid
        let title = f.title.replace('|', "\\|");
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} | {:.0}/10 |\n",
            i + 1,
            sev,
            title,
            ids,
            loc,
            f.risk_score()
        ));
    }

    if findings.len() > max_show {
        md.push_str(&format!(
            "| | | _+ {} more findings…_ | | | |\n",
            findings.len() - max_show
        ));
    }

    // Remediation highlights for the top 5
    let critical_high: Vec<&Finding> = findings
        .iter()
        .filter(|f| f.severity == Severity::Critical || f.severity == Severity::High)
        .collect();

    if !critical_high.is_empty() {
        md.push_str("\n### 🔧 Suggested fixes\n\n");
        for f in critical_high.iter().take(5) {
            md.push_str(&format!("- **{}** — ", f.title));
            if let Some(fp) = f.file_path.as_deref() {
                md.push_str(&format!("`{}`", fp));
                if let Some(ln) = f.line_number {
                    md.push_str(&format!(":{}", ln));
                }
                md.push_str(" — ");
            }
            md.push_str(
                f.remediation
                    .as_deref()
                    .unwrap_or("Review and fix manually."),
            );
            md.push('\n');
        }
    }

    md.push_str("\n---\n");
    md.push_str(&format!(
        "_[View full report](https://github.com/{}/actions) · Run `cipher-ai review --format sarif` for machine-readable output._\n",
        repo
    ));

    md
}

/// GitHub comment request body.
#[derive(Serialize)]
struct CommentBody {
    body: String,
}

/// Post a comment to a GitHub pull request.
pub(crate) async fn post_pr_comment(
    repo: &str,
    pr_number: u32,
    token: &str,
    body: &str,
) -> Result<()> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .user_agent("cipher-ai/1.0")
        .build()
        .context("Failed to build HTTP client")?;

    let url = format!("{}/repos/{}/issues/{}/comments", GITHUB_API, repo, pr_number);

    let response = client
        .post(&url)
        .bearer_auth(token)
        .header("Accept", "application/vnd.github+json")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .json(&CommentBody { body: body.to_string() })
        .send()
        .await
        .context("Failed to send comment to GitHub")?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        anyhow::bail!(
            "GitHub API error ({}) posting to {}#{}: {}",
            status,
            repo,
            pr_number,
            text
        );
    }

    Ok(())
}

/// Resolve the repo (owner/name) from CLI arg or environment.
pub(crate) fn resolve_repo(repo: Option<&str>) -> Option<String> {
    repo.map(|s| s.to_string())
        .or_else(|| std::env::var("GITHUB_REPOSITORY").ok())
}

/// Extract `owner/name` from a git remote URL.
///
/// Handles `https://github.com/owner/repo.git` and `git@github.com:owner/repo.git`
/// forms. Returns `None` when the URL isn't a recognizable GitHub remote.
pub(crate) fn repo_from_remote_url(remote: &str) -> Option<String> {
    let trimmed = remote.trim();
    if trimmed.is_empty() {
        return None;
    }
    // Strip the protocol/prefix to isolate the path component.
    let path = trimmed
        .split("github.com")
        .nth(1)?
        .trim_start_matches(':')
        .trim_start_matches('/');
    let path = path.trim_end_matches(".git").trim_end_matches('/');
    if path.is_empty() {
        return None;
    }
    let mut parts: Vec<&str> = path.split('/').filter(|p| !p.is_empty()).collect();
    if parts.len() < 2 {
        return None;
    }
    let name = parts.pop().unwrap_or_default();
    let owner = parts.pop().unwrap_or_default();
    if owner.is_empty() || name.is_empty() {
        return None;
    }
    Some(format!("{}/{}", owner, name))
}

/// Body of a pull-request creation request.
#[derive(Serialize)]
struct CreatePullRequest {
    title: String,
    head: String,
    base: String,
    body: String,
}

/// Create a pull request on GitHub and return its HTML URL.
pub(crate) async fn create_pull_request(
    repo: &str,
    token: &str,
    head: &str,
    base: &str,
    title: &str,
    body: &str,
) -> Result<String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .user_agent("cipher-ai/1.0")
        .build()
        .context("Failed to build HTTP client")?;

    let url = format!("{}/repos/{}/pulls", GITHUB_API, repo);
    let payload = CreatePullRequest {
        title: title.to_string(),
        head: head.to_string(),
        base: base.to_string(),
        body: body.to_string(),
    };

    let response = client
        .post(&url)
        .bearer_auth(token)
        .header("Accept", "application/vnd.github+json")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .json(&payload)
        .send()
        .await
        .context("Failed to send pull request to GitHub")?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        anyhow::bail!(
            "GitHub API error ({}) creating PR on {}: {}",
            status,
            repo,
            text
        );
    }

    let json: serde_json::Value = response.json().await?;
    Ok(json
        .get("html_url")
        .and_then(|v| v.as_str())
        .unwrap_or(&url)
        .to_string())
}

/// Get the default branch of a repository (used as the PR base).
pub(crate) async fn default_branch(repo: &str, token: &str) -> Option<String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .user_agent("cipher-ai/1.0")
        .build()
        .ok()?;
    let url = format!("{}/repos/{}", GITHUB_API, repo);
    let response = client
        .get(&url)
        .bearer_auth(token)
        .header("Accept", "application/vnd.github+json")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .send()
        .await
        .ok()?;
    if !response.status().is_success() {
        return None;
    }
    let json: serde_json::Value = response.json().await.ok()?;
    json.get("default_branch")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
}

/// Resolve the PR number from CLI arg or environment (GITHUB_PR_NUMBER,
/// or parse GITHUB_REF `refs/pull/N/merge`).
fn resolve_pr_number(pr_number: Option<u32>) -> Option<u32> {
    if let Some(n) = pr_number {
        return Some(n);
    }
    if let Ok(n) = std::env::var("GITHUB_PR_NUMBER") {
        if let Ok(parsed) = n.parse::<u32>() {
            return Some(parsed);
        }
    }
    if let Ok(github_ref) = std::env::var("GITHUB_REF") {
        // refs/pull/42/merge
        let parts: Vec<&str> = github_ref.split('/').collect();
        if parts.len() >= 3 && parts[0] == "refs" && parts[1] == "pull" {
            if let Ok(parsed) = parts[2].parse::<u32>() {
                return Some(parsed);
            }
        }
    }
    None
}

/// A file changed in a pull request (from the GitHub files API).
#[derive(Debug, Clone)]
pub(crate) struct ChangedFile {
    pub path: String,
    /// Unified-diff patch for this file (absent for binary/large files)
    pub patch: Option<String>,
}

/// Fetch the list of files changed in a pull request.
///
/// Calls `GET /repos/{repo}/pulls/{number}/files`. Used by `pr --diff` to
/// restrict review comments to the lines this PR actually touches.
pub(crate) async fn get_pr_changed_files(
    repo: &str,
    token: &str,
    pr_number: u32,
) -> Result<Vec<ChangedFile>> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .user_agent("cipher-ai/1.0")
        .build()
        .context("Failed to build HTTP client")?;

    #[derive(Deserialize)]
    struct RawFile {
        filename: String,
        patch: Option<String>,
    }

    // The files API returns at most 100 results per page. Keep fetching pages
    // until a page comes back short (GitHub returns an empty array past the
    // end), so PRs with more than 100 changed files are fully covered.
    let mut all = Vec::new();
    let mut page = 1u32;
    loop {
        let url = format!(
            "{}/repos/{}/pulls/{}/files?per_page=100&page={}",
            GITHUB_API, repo, pr_number, page
        );
        let response = client
            .get(&url)
            .bearer_auth(token)
            .header("Accept", "application/vnd.github+json")
            .header("X-GitHub-Api-Version", "2022-11-28")
            .send()
            .await
            .context("Failed to fetch PR files from GitHub")?;

        if !response.status().is_success() {
            let status = response.status();
            let text = response.text().await.unwrap_or_default();
            anyhow::bail!(
                "GitHub API error ({}) fetching files for {}#{}: {}",
                status,
                repo,
                pr_number,
                text
            );
        }

        let files: Vec<RawFile> = response.json().await?;
        let count = files.len();
        all.extend(files.into_iter().map(|f| ChangedFile {
            path: f.filename,
            patch: f.patch,
        }));
        if count < 100 {
            break;
        }
        page += 1;
    }

    Ok(all)
}

/// Parse the 1-based new-file line numbers of *added* lines in a unified diff.
///
/// Added lines are the ones this PR introduces — the only lines we want to
/// flag in a review. Handles `@@ -old,oldcount +new,newcount @@` hunk headers.
pub(crate) fn parse_added_lines(patch: &str) -> Vec<usize> {
    let mut added = Vec::new();
    let mut new_line: Option<usize> = None;

    for line in patch.lines() {
        if line.starts_with("@@") {
            let header = line.trim_start_matches("@@").trim_end_matches("@@");
            // header: ` -3,7 +10,3 ` — we want the new-file start after '+'
            let new_start = header
                .split('+')
                .nth(1)
                .and_then(|s| s.split(',').next())
                .and_then(|s| s.trim().parse::<usize>().ok());
            new_line = new_start;
            continue;
        }
        let Some(n) = new_line else { continue };
        if line.starts_with("+++") || line.starts_with("---") {
            continue; // file headers, not hunks
        }
        if line.starts_with('+') {
            added.push(n);
            new_line = Some(n + 1);
        } else if line.starts_with('-') {
            // removed line — consumes no new-file line number
        } else if line.starts_with('\\') {
            // `\ No newline at end of file` marker — consumes no line number
        } else {
            // context line — occupies a new-file line number
            new_line = Some(n + 1);
        }
    }

    added
}

/// Find the changed file whose path matches a finding's file path.
///
/// Case-insensitive exact match, or suffix match so absolute finding paths
/// (e.g. `/proj/src/app.js`) line up with repo-relative changed-file paths
/// (`src/app.js`).
pub(crate) fn match_changed_file<'a>(fp: &str, files: &'a [ChangedFile]) -> Option<&'a ChangedFile> {
    let fp_norm = fp.replace('\\', "/").to_lowercase();
    files.iter().find(|cf| {
        let cf_norm = cf.path.replace('\\', "/").to_lowercase();
        cf_norm == fp_norm || fp_norm.ends_with(&format!("/{}", cf_norm))
    })
}

/// Split findings into those introduced by the PR's diff and pre-existing ones.
///
/// A finding is "in the diff" when its file is among the PR's changed files
/// AND its line is one of the added lines (findings without a patch or line
/// number fall back to a file-level match so nothing is silently dropped).
/// Returns `(in_diff, preexisting)`.
pub(crate) fn split_by_diff(
    findings: Vec<Finding>,
    files: &[ChangedFile],
) -> (Vec<Finding>, Vec<Finding>) {
    let mut in_diff = Vec::new();
    let mut preexisting = Vec::new();

    for f in findings {
        let Some(fp) = f.file_path.as_deref() else {
            preexisting.push(f);
            continue;
        };
        let Some(cf) = match_changed_file(fp, files) else {
            preexisting.push(f);
            continue;
        };

        let is_added = match (cf.patch.as_deref(), f.line_number) {
            (Some(patch), Some(ln)) => parse_added_lines(patch).contains(&ln),
            // No patch (binary/large) or no line number: file-level match counts
            _ => true,
        };
        if is_added {
            in_diff.push(f);
        } else {
            preexisting.push(f);
        }
    }

    (in_diff, preexisting)
}

/// Build the inline review comments (path, line, body) for critical/high
/// findings that have a file path and line number. Findings in changed files
/// without a patch (binary/large files) are skipped — GitHub cannot position
/// comments there and would reject the whole review. Capped at 10 comments.
fn build_inline_comments(findings: &[Finding], files: &[ChangedFile]) -> Vec<(String, usize, String)> {
    findings
        .iter()
        .filter(|f| f.severity == Severity::Critical || f.severity == Severity::High)
        .filter(|f| {
            // Skip patchless files (binary/large) so post_review_comments can't
            // 422 the entire request on an unpositionable line.
            let Some(fp) = f.file_path.as_deref() else {
                return false;
            };
            match match_changed_file(fp, files) {
                Some(cf) => cf.patch.is_some(),
                // No changed file matched — only happens when the diff fetch
                // failed (changed_files empty). No positionable comments exist
                // then, so exclude everything rather than 422 the review.
                None => false,
            }
        })
        .filter_map(|f| {
            let path = f.file_path.clone()?;
            let line = f.line_number?;
            let cwe = f.cwe_id.clone().unwrap_or_else(|| "no CWE".to_string());
            let body = format!(
                "**{}** ({}) · {}\n\n{}",
                f.title,
                f.severity,
                cwe,
                f.remediation
                    .clone()
                    .unwrap_or_else(|| "Review this finding manually.".to_string())
            );
            Some((path, line, body))
        })
        .take(10)
        .collect()
}

/// Post inline review comments at specific file:line positions.
///
/// Uses the GitHub reviews API (`POST /repos/{repo}/pulls/{n}/reviews`) so the
/// comments appear directly on the changed lines, not just as one summary.
/// `comments` is `(path, line, body)` tuples; no-ops when empty.
pub(crate) async fn post_review_comments(
    repo: &str,
    token: &str,
    pr_number: u32,
    comments: &[(String, usize, String)],
) -> Result<()> {
    if comments.is_empty() {
        return Ok(());
    }

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .user_agent("cipher-ai/1.0")
        .build()
        .context("Failed to build HTTP client")?;

    #[derive(Serialize)]
    struct ReviewComment {
        path: String,
        line: usize,
        body: String,
    }

    #[derive(Serialize)]
    struct ReviewBody {
        event: String,
        body: String,
        comments: Vec<ReviewComment>,
    }

    let url = format!("{}/repos/{}/pulls/{}/reviews", GITHUB_API, repo, pr_number);
    let body = ReviewBody {
        event: "COMMENT".to_string(),
        body: format!("🔒 CipherAI found {} issue(s) in this diff.", comments.len()),
        comments: comments
            .iter()
            .map(|(path, line, text)| ReviewComment {
                path: path.clone(),
                line: *line,
                body: text.clone(),
            })
            .collect(),
    };

    let response = client
        .post(&url)
        .bearer_auth(token)
        .header("Accept", "application/vnd.github+json")
        .header("X-GitHub-Api-Version", "2022-11-28")
        .json(&body)
        .send()
        .await
        .context("Failed to post review comments")?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        anyhow::bail!(
            "GitHub API error ({}) posting review to {}#{}: {}",
            status,
            repo,
            pr_number,
            text
        );
    }
    Ok(())
}

/// Run the `cipher-ai pr` command — review a pull request and comment.
///
/// With `--diff`, fetches the PR's changed files and only reports findings that
/// touch lines this PR introduces (pre-existing issues are summarized but not
/// commented on), and posts inline comments on the changed lines.
pub async fn run_pr(
    project_path: &Path,
    repo: Option<&str>,
    pr_number: Option<u32>,
    token: Option<&str>,
    dry_run: bool,
    diff_only: bool,
) -> Result<()> {
    let canonical_path = std::fs::canonicalize(project_path)?;

    output::print_header("PR Security Review", Some(&canonical_path.display().to_string()));

    // Resolve repo + PR number
    let repo = match resolve_repo(repo) {
        Some(r) => r,
        None => {
            anyhow::bail!(
                "Could not determine repository. Pass --repo owner/name or set GITHUB_REPOSITORY."
            )
        }
    };
    let pr_number = match resolve_pr_number(pr_number) {
        Some(n) => n,
        None => {
            anyhow::bail!(
                "Could not determine PR number. Pass --pr N or set GITHUB_PR_NUMBER / GITHUB_REF."
            )
        }
    };
    let token = match token {
        Some(t) => t.to_string(),
        None => match std::env::var("GITHUB_TOKEN").or_else(|_| std::env::var("GH_TOKEN")) {
            Ok(t) => t,
            Err(_) => anyhow::bail!(
                "No GitHub token found. Pass --token or set GITHUB_TOKEN.\n\
                 Tokens need the `repo` scope to comment on PRs."
            ),
        },
    };

    println!(
        "  {} Reviewing {} #{}...\n",
        "[GITHUB]".cyan(),
        repo.yellow(),
        pr_number.to_string().yellow().bold()
    );

    let total_steps = if diff_only { 5 } else { 3 };

    // Step 1: run the scan suite
    output::print_step(1, total_steps, "Running security scans (review + secrets + deps + zeroday)");
    let (findings, attack_count) = collect_pr_findings(&canonical_path).await?;
    let (critical, high, medium, low) = severity_counts(&findings);
    output::print_ok("Scans", &format!(
        "{} critical, {} high, {} medium, {} low, {} total",
        critical.to_string().red().bold(),
        high.to_string().yellow().bold(),
        medium.to_string().cyan(),
        low.to_string().dimmed(),
        findings.len().to_string().bold()
    ));

    // Step 2 (diff-aware only): fetch changed files and filter findings
    let mut findings = findings;
    let mut preexisting: Vec<Finding> = Vec::new();
    let mut changed_files: Vec<ChangedFile> = Vec::new();
    if diff_only {
        output::print_step(2, total_steps, "Fetching PR changed files");
        match get_pr_changed_files(&repo, &token, pr_number).await {
            Ok(files) => {
                let (in_diff, pre) = split_by_diff(findings, &files);
                findings = in_diff;
                preexisting = pre;
                changed_files = files;
                output::print_ok("Diff", &format!(
                    "{} finding(s) in this PR's changes, {} pre-existing",
                    findings.len(),
                    preexisting.len()
                ));
            }
            Err(e) => {
                output::print_warn("Diff", &format!(
                    "could not fetch changed files ({}); reviewing full repository",
                    e
                ));
            }
        }
    }

    // Step 3 (or 2): render the comment
    let render_step = if diff_only { 3 } else { 2 };
    output::print_step(render_step, total_steps, "Rendering review comment");
    let comment = render_pr_comment(&findings, attack_count, &repo, pr_number);

    // Dry-run: preview the summary comment AND the inline comments that would
    // be posted, so the preview shows exactly what the review will contain.
    if dry_run {
        output::print_step(total_steps, total_steps, "Dry-run mode — nothing posted");
        println!();
        println!("{}", comment);
        if !preexisting.is_empty() {
            println!();
            println!(
                "  {} {} pre-existing finding(s) outside this diff were excluded from the review.",
                "[NOTE]".bold(),
                preexisting.len().to_string().cyan()
            );
        }
        if diff_only {
            let inline = build_inline_comments(&findings, &changed_files);
            if !inline.is_empty() {
                println!();
                println!("  {} {} inline comment(s) would be posted:", "[INLINE]".bold().cyan(), inline.len().to_string().cyan());
                for (path, line, body) in &inline {
                    println!("    {} {}:{}", "->".cyan(), path.yellow(), line);
                    for l in body.lines().take(3) {
                        println!("      {}", l.dimmed());
                    }
                    println!();
                }
            }
        }
        println!();
        output::print_ok("Dry-run", "Rerun without --dry-run to post this review to the PR.");
        return Ok(());
    }

    // Step 4 (diff-aware only): post inline comments on changed lines
    if diff_only {
        output::print_step(4, total_steps, "Posting inline review comments");
        let inline = build_inline_comments(&findings, &changed_files);
        if inline.is_empty() {
            output::print_ok("Inline", "no critical/high findings in the diff");
        } else {
            match post_review_comments(&repo, &token, pr_number, &inline).await {
                Ok(()) => output::print_ok("Inline", &format!("{} comment(s) posted", inline.len())),
                Err(e) => output::print_warn("Inline", &format!("could not post inline comments ({})", e)),
            }
        }
    }

    let post_step = if diff_only { 5 } else { 3 };
    output::print_step(post_step, total_steps, "Posting summary comment to GitHub");
    match post_pr_comment(&repo, pr_number, &token, &comment).await {
        Ok(()) => {
            output::print_success(&format!(
                "Comment posted to {}/pull/{}",
                repo,
                pr_number
            ));
        }
        Err(e) => {
            output::print_fail("GitHub", &e.to_string());
            anyhow::bail!(e);
        }
    }

    output::print_footer();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finding::{Confidence, FindingType};

    fn mk(title: &str, sev: Severity, cwe: &str, file: &str, line: usize) -> Finding {
        Finding::new(
            FindingType::Vulnerability,
            title,
            "desc",
            sev,
            Confidence::High,
            "test",
        )
        .at(file, line)
        .with_cwe(cwe)
    }

    #[test]
    fn test_severity_counts() {
        let findings = vec![
            mk("A", Severity::Critical, "CWE-89", "a.py", 1),
            mk("B", Severity::High, "CWE-78", "b.py", 2),
            mk("C", Severity::Medium, "CWE-22", "c.py", 3),
            mk("D", Severity::Low, "CWE-79", "d.py", 4),
        ];
        let (c, h, m, l) = severity_counts(&findings);
        assert_eq!((c, h, m, l), (1, 1, 1, 1));
    }

    #[test]
    fn test_render_pr_comment_empty() {
        let md = render_pr_comment(&[], 0, "owner/repo", 1);
        assert!(md.contains("No security issues found"));
        assert!(md.contains("PR #1"));
    }

    #[test]
    fn test_render_pr_comment_with_findings() {
        let findings = vec![
            mk("SQL Injection in query", Severity::Critical, "CWE-89", "app/query.py", 42),
            mk("Weak MD5 hash", Severity::High, "CWE-328", "app/hash.py", 7),
        ];
        let md = render_pr_comment(&findings, 3, "owner/repo", 12);
        assert!(md.contains("PR #12"));
        assert!(md.contains("CWE-89"));
        assert!(md.contains("SQL Injection"));
        assert!(md.contains("3 taint/attack chains"));
        assert!(md.contains("Suggested fixes"));
    }

    #[test]
    fn test_resolve_pr_number_env() {
        // Env var path
        std::env::set_var("GITHUB_PR_NUMBER", "42");
        assert_eq!(resolve_pr_number(None), Some(42));
        std::env::remove_var("GITHUB_PR_NUMBER");

        // GITHUB_REF path
        std::env::set_var("GITHUB_REF", "refs/pull/99/merge");
        assert_eq!(resolve_pr_number(None), Some(99));
        std::env::remove_var("GITHUB_REF");

        // Explicit arg wins
        std::env::set_var("GITHUB_PR_NUMBER", "42");
        assert_eq!(resolve_pr_number(Some(7)), Some(7));
        std::env::remove_var("GITHUB_PR_NUMBER");
    }

    #[test]
    fn test_parse_added_lines_simple() {
        let patch = "@@ -1,3 +1,4 @@\n fn existing() {\n-    let x = 1;\n+    let x = 2;\n+    exec(x);\n }\n";
        let added = parse_added_lines(patch);
        assert_eq!(added, vec![2, 3]);
    }

    #[test]
    fn test_parse_added_lines_multiple_hunks() {
        let patch = "@@ -5,2 +5,2 @@\n a\n+ b\n@@ -20,1 +21,1 @@\n+ c\n";
        let added = parse_added_lines(patch);
        assert_eq!(added, vec![6, 21]);
    }

    #[test]
    fn test_parse_added_lines_empty() {
        assert!(parse_added_lines("").is_empty());
        assert!(parse_added_lines("no hunks here").is_empty());
    }

    #[test]
    fn test_parse_added_lines_no_newline_marker() {
        // `\ No newline at end of file` must not shift subsequent line numbers
        let patch = "@@ -1,2 +1,3 @@\n a\n+    exec(x);\n\\ No newline at end of file\n";
        let added = parse_added_lines(patch);
        assert_eq!(added, vec![2]);
    }

    #[test]
    fn test_split_by_diff_keeps_added_lines() {
        let files = vec![ChangedFile {
            path: "src/app.js".to_string(),
            patch: Some("@@ -1,2 +1,3 @@\n a\n+    exec(x);\n b\n".to_string()),
        }];
        let findings = vec![
            mk("Command Injection", Severity::Critical, "CWE-78", "src/app.js", 2),
            mk("Weak hash", Severity::Medium, "CWE-328", "src/app.js", 1),
            mk("Old issue", Severity::Low, "CWE-693", "src/other.js", 5),
        ];
        let (in_diff, preexisting) = split_by_diff(findings, &files);
        assert_eq!(in_diff.len(), 1);
        assert_eq!(in_diff[0].title, "Command Injection");
        assert_eq!(preexisting.len(), 2);
    }

    #[test]
    fn test_split_by_diff_file_level_fallback() {
        // No patch (binary/large file) → file-level match counts
        let files = vec![ChangedFile {
            path: "src/app.js".to_string(),
            patch: None,
        }];
        let findings = vec![mk("Secret", Severity::High, "CWE-798", "src/app.js", 9)];
        let (in_diff, preexisting) = split_by_diff(findings, &files);
        assert_eq!(in_diff.len(), 1);
        assert!(preexisting.is_empty());
    }

    #[test]
    fn test_split_by_diff_path_suffix_match() {
        // Finding paths may be absolute; changed-file paths are repo-relative
        let files = vec![ChangedFile {
            path: "src/app.js".to_string(),
            patch: Some("@@ -1,1 +1,2 @@\n a\n+  bug();\n".to_string()),
        }];
        let findings = vec![mk("Bug", Severity::High, "CWE-693", "/proj/src/app.js", 2)];
        let (in_diff, _) = split_by_diff(findings, &files);
        assert_eq!(in_diff.len(), 1);
    }

    #[test]
    fn test_build_inline_comments_skips_patchless_files() {
        // Findings in binary/large changed files (no patch) must NOT produce
        // inline comments — GitHub can't position them and would reject the
        // whole review request with a 422.
        let files = vec![
            ChangedFile {
                path: "src/app.js".to_string(),
                patch: Some("@@ -1,1 +1,2 @@\n a\n+  bug();\n".to_string()),
            },
            ChangedFile {
                path: "assets/big.bin".to_string(),
                patch: None,
            },
        ];
        let findings = vec![
            mk("Bug", Severity::High, "CWE-693", "src/app.js", 2),
            mk("Secret in binary", Severity::Critical, "CWE-798", "assets/big.bin", 5),
        ];
        let inline = build_inline_comments(&findings, &files);
        assert_eq!(inline.len(), 1);
        assert_eq!(inline[0].0, "src/app.js");
    }

    #[test]
    fn test_build_inline_comments_empty_changed_files() {
        // When the diff fetch failed (empty changed_files), no comments can be
        // positioned — the function must return nothing rather than 422.
        let findings = vec![mk("Bug", Severity::High, "CWE-693", "src/app.js", 2)];
        assert!(build_inline_comments(&findings, &[]).is_empty());
    }

    #[test]
    fn test_repo_from_remote_url_https() {
        assert_eq!(
            repo_from_remote_url("https://github.com/owner/repo.git"),
            Some("owner/repo".to_string())
        );
    }

    #[test]
    fn test_repo_from_remote_url_ssh() {
        assert_eq!(
            repo_from_remote_url("git@github.com:owner/repo.git"),
            Some("owner/repo".to_string())
        );
    }

    #[test]
    fn test_repo_from_remote_url_nested() {
        assert_eq!(
            repo_from_remote_url("https://github.com/org/team/app.git"),
            Some("team/app".to_string())
        );
    }

    #[test]
    fn test_repo_from_remote_url_invalid() {
        assert_eq!(repo_from_remote_url(""), None);
        assert_eq!(repo_from_remote_url("not a github url"), None);
    }

    #[test]
    fn test_render_comment_escapes_pipes() {
        let mut f = mk("A | B", Severity::High, "CWE-89", "a.py", 1);
        f.title = "Injection | Danger".to_string();
        let md = render_pr_comment(&[f], 0, "o/r", 5);
        assert!(md.contains("Injection \\| Danger"));
    }
}
